### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by coderofmutou** [RichardAth/Projects#1]
This can only decompose a relatively small number, can break down a more than four hundred diags ,with more than two prime product?

**Comment by RichardAth** [comment]
I can't give an exact limit for the size of number to be factored. 
The time taken generally depends on the size of the 2nd largest factor; once the smaller factors are found we can use Miller-Rabin to test the unfactored residue, even on very large numbers. If the residue is prime if we are done. 
If we are lucky and there is only one very large factor the factorisation is quite quick, but if there is more than one prime factor > about 30 decimal digits the time required can increase to hours or even days.
 
So, to get back to your original question, for random numbers with > 400 digits the time required might be days, and cannot be estimated accurately in advance.

**Comment by coderofmutou** [comment]
I use Alpertron_Calculate. n=550167741302968195769819414828859082026511587458002285631287495831856132679007143691206492321988954001297916189554068549927049647558583001220942719635296457354402445313160938157115514162931809800354138071640431997629358309550505318888086712562549900671837754158618336312724819122779660939224394363445649845312288078285113068784296092816480347516881848191082051079173942231460201630149708910589634098858042889761555259
，The error is File：minkernel\crts\ucrt\src\sppcrt\stdio\gets.cpp ，Line：103 ，expression:(L"Buffer is too small" && 0)

**Comment by coderofmutou** [comment]
OhOh，I know the problem is that the input array is only 160 in length，So can't input the number I want to input.

**Comment by coderofmutou** [comment]
Could you tell me what's the method you used? ECM or GNFS or some else?

**Comment by RichardAth** [comment]
The program uses ECM or SIQS depending on the number size. In this case it is using ECM. I tried factorising the number and after 10 minutes I got the following output, which indicates that it has found several factors. The program is still running.

 

Compiled on Jun  4 2018 at 14:59:34

enter expression to be processed, or HELP, or EXIT

550167741302968195769819414828859082026511587458002285631287495831856132679007143691206492321988954001297916189554068549927049647558583001220942719635296457354402445313160938157115514162931809800354138071640431997629358309550505318888086712562549900671837754158618336312724819122779660939224394363445649845312288078285113068784296092816480347516881848191082051079173942231460201630149708910589634098858042889761555259

 

= 550 167741 302968 195769 819414 828859 082026 511587 458002 285631 287495 831856 132679 007143 691206 492321 988954 001297 916189 554068 549927 049647 558583 001220 942719 635296 457354 402445 313160 938157 115514 162931 809800 354138 071640 431997 629358 309550 505318 888086 712562 549900 671837 754158 618336 312724 819122 779660 939224 394363 445649 845312 288078 285113 068784 296092 816480 347516 881848 191082 051079 173942 231460 201630 149708 910589 634098 858042 889761 555259 (417 digits)

Expected no of primes is 33093

  prime     33335 is      393209

0d 0h 0m 8.3s  ECM Curve 25 using bounds B1=2000 and B2=200000

0d 0h 0m 16.5s  ECM Curve 26 using bounds B1=50000 and B2=5000000

Time elapsed: 0d 0h 0m 18s Step 1: 38%

0d 0h 0m 57.4s  ECM Curve 30 using bounds B1=50000 and B2=5000000

Time elapsed: 0d 0h 1m 0s Step 1: 64%%

0d 0h 3m 39.4s  ECM Curve 49 using bounds B1=50000 and B2=5000000

Time elapsed: 0d 0h 3m 42s Step 1: 70%

0d 0h 6m 25.2s  ECM Curve 50 using bounds B1=50000 and B2=5000000

Time elapsed: 0d 0h 6m 30s Step 2: 40%

0d 0h 12m 3.6s  ECM Curve 81 using bounds B1=50000 and B2=50000000

**Comment by RichardAth** [comment]
Using Dario Alpert’s web-based calculator at https://www.alpertron.com.ar/ECM.HTM, which gives more information about its progress, I got the following five factors after 35 minutes:

550 167741 302968 195769 819414 828859 082026 511587 458002 285631 287495 831856 132679 007143 691206 492321 988954 001297 916189 554068 549927 049647 558583 001220 942719 635296 457354 402445 313160 938157 115514 162931 809800 354138 071640 431997 629358 309550 505318 888086 712562 549900 671837 754158 618336 312724 819122 779660 939224 394363 445649 845312 288078 285113 068784 296092 816480 347516 881848 191082 051079 173942 231460 201630 149708 910589 634098 858042 889761 555259 (417 digits) 

= 1 732792 378957 × 832 328713 672817 × 952921 534336 737871 × 1309 672216 786572 122317 × 1 208925 819614 750508 040051 × 

252 833319 625948 070719 863769 826948 834186 048301 804162 717998 576735 124149 975909 316512 549784 889029 061331 846830 143984 

754164 313343 005494 100364 534328 464509 084094 464193 681742 034308 361602 107128 798022 946709 843588 082950 516475 082499 

497616 934464 177692 722885 827416 818929 430991 616386 422962 088297 557012 776579 260013 299657 434780 825704 332797 381423 (327 digits)

Factoring 252 833319 625948 070719 863769 826948 834186 048301 804162 717998 576735 124149 975909 316512 549784 889029 061331 846830 143984 754164 313343 005494 100364 534328 464509 084094 464193 681742 034308 361602 107128 798022 946709 843588 082950 516475 082499 497616 934464 177692 722885 827416 818929 430991 616386 422962 088297 557012 776579 260013 299657 434780 825704 332797 381423 (327 digits)

Curve 231 using bounds B1=50000 and B2=5000000

Time elapsed: 0d 0h 30m 25s    Step 2: 68%

**Comment by coderofmutou** [comment]
Where are you come from，I think maybe we can talk with aother way...

**Comment by coderofmutou** [comment]
I have seen the Web page and the code,  I'm very interested in it. Thank you very much. Now what should I do maybe is to carefully study and understand the code.

**Comment by coderofmutou** [comment]
Today, I ran for more than ten hours on my personal computer in the website, but it did not have a result. Can you tell me the performance of the server you are using? And than I study the code downloaded on the website, but I don't know whether it is running under linux or under Windows. I compile with vs2017 on Windows and loaded the SDL library, but it didn't work.

**Comment by coderofmutou** [comment]
I am a sophomore student from China who recently did a research on Integer factorization with the teacher. I'm very intested in  Integer factorization. Thank you for your great help a few days ago. And now I have used the code you write to factor a 212-digits number for many days, but it seems to don't work. Do you have any suggestions to me? Thanks. The number is 19723931666763821627700426954447542247412038447494167392379203106109861439365094940480211202360936482364086385728883398972852332045306821877668507029329392860876326057301111753015945483412407195193903018805868917.

**Comment by RichardAth** [comment]
I cannot really suggest anything. The Wikipedia article at https://en.wikipedia.org/wiki/Integer_factorization suggests that in general numbers this large cannot be factored in a reasonable amount of time, unless you already know something special about the properties of the number. Clearly it does not have many small factors.

 

You could try looking in another website such as http://mersennewiki.org <http://mersennewiki.org/>  

Although mostly interested in Mersenne primes, it has some general prime-solving descriptions and links that might be useful.
